version: '3.8'

services:
  app:
    build: .
    container_name: php-app
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    restart: always
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: minhasenha123
      MYSQL_DATABASE: clientes
      MYSQL_USER: user_docker
      MYSQL_PASSWORD: suasenha_user
    volumes:
      - db_data:/var/lib/mysql
      - ./clientes.sql:/docker-entrypoint-initdb.d/clientes.sql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-app
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: minhasenha123
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data: